openapi: 3.0.3
info:
  title: Software Engineering Project
  description: IIT Madras - BS Degree - Online Support Ticketing System
  contact:
    email: 21f1006019@ds.study.iitm.ac.in
  version: 1.0.11
servers:
  - url: https://SE-Project.ansh-kushwaha.repl.co
    variables: {}
tags:
  - name: HomePage
    description: Operations on HomePage
  - name: User
    description: Operations about User
  - name: Ticket
    description: Operations on Ticket
  - name: Content
    description: Operations on Content
  - name: Like
    description: Operations about Like
paths:
  /:
    description: HomeApi
    get:
      summary: Display homepage
      description: fetch homepage
      operationId: '1'
      responses:
        '203':
          description: success
          content:
            application/json:
              examples:
                Sample 203 Response:
                  value:
                    Home Page: Login to Proceed
        '404':
          description: Page not found
          content:
            application/json:
              examples:
                Example 404 Response:
                  value: Page not found
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example 500 Response:
                  value: Internal Server Error
      tags:
        - HomePage
    post:
      summary: Redirect to login
      description: Sign up/ login
      operationId: '2'
      responses:
        '200':
          description: Login Successful
          content:
            application/json:
              examples:
                Example Response 200:
                  value:
                    Login Successful: Welcome
        '201':
          description: Registered Succesfully
          content:
            application/json:
              examples:
                Example 201 Response:
                  value:
                    User Registered Successfully: Wait for Approval
        '401':
          description: Credentials are incorrect
          content:
            application/json:
              examples:
                Example Response 401:
                  value:
                    Incorrect Password: Try Again
        '403':
          description: Already a user!
          content:
            application/json:
              examples:
                Example Response 403:
                  value:
                    User Already Exists: Go Back & Login
        '404':
          description: User not found
          content:
            application/json:
              examples:
                Example Response 404:
                  value:
                    Unregistered User: Go Back & Register
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - HomePage
  /user:
    summary: User API
    get:
      summary: Fetch all users
      description: Get and Post
      operationId: '3'
      responses:
        '203':
          description: All active users
          content:
            application/json:
              examples:
                Example Response 203:
                  value:
                    email: abcd@iitm.ac.in
                    password: xxxxxxxx
                    role: 1
                    status: 0
        '401':
          description: Access not possible
          content:
            application/json:
              examples:
                Example Response 203:
                  value: Access Denied
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - User
    post:
      summary: Add details of user
      description: register
      operationId: '4'
      responses:
        '203':
          description: success
          content:
            application/json:
              examples:
                Example Response 203:
                  value:
                    email: abcd@iitm.ac.in
                    password: cdsgdjfnf
                    role: 0
        '403':
          description: Unable to figure out
          content:
            application/json:
              examples:
                Example 403 response:
                  value: ''
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - User
  /user/{email}:
    summary: Get, Edit & Delete
    get:
      summary: Returns User
      description: returns user
      operationId: ''
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '203':
          description: All active users
          content:
            application/json:
              examples:
                Example Response 203:
                  value:
                    email: abcd@iitm.ac.in
                    password: xxxxxxxx
                    role: 1
                    status: 0
        '401':
          description: Access not possible
          content:
            application/json:
              examples:
                Example Response 203:
                  value: Access Denied
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
        default:
          description: Default error sample response
      tags:
        - User
    put:
      summary: Update User
      description: user update
      operationId: '5'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '203':
          description: Updating User
          content:
            application/json:
              examples:
                Example Response 203:
                  value:
                    email: abcd@iitm.ac.in
                    password: cdsgdjfnf
                    role: 0
                    status: 1
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '403':
          description: Something went wrong
          content:
            application/json:
              examples:
                Example response 403:
                  value: ''
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - User
    delete:
      summary: Delete user
      description: Delete a user if not approved
      operationId: '7'
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Content deleted
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '403':
          description: Something went wrong
          content:
            application/json:
              examples:
                Example response 403:
                  value: ''
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - User
  /ticket:
    description: Ticket API
    get:
      summary: Get ticket details
      description: Get AND Post
      operationId: '8'
      responses:
        '201':
          description: Details
          content:
            application/json:
              examples:
                Example Response 201:
                  value:
                    id: 7
                    user_email: abcde@iitm.ac.in
                    title: week-8 discussion
                    status: 1
                    likes: 24
                    is_faq: 0
                    timestamp: '''2023-01-19 03:14:07'
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - Ticket
    post:
      summary: Add ticket details
      description: ''
      operationId: '10'
      responses:
        '201':
          description: Success
          content:
            application/json:
              examples:
                Example Response 201:
                  value:
                    user_email: abc@iitm.ac.in
                    title: week-9 problem
                    tags: '@arvind'
                    desc: abcd
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - Ticket
  /ticket/{id}:
    description: Fetch, Update and Delete
    get:
      summary: Get Ticket
      description: returns ticket
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Details
          content:
            application/json:
              examples:
                Example Response 201:
                  value:
                    id: 7
                    user_email: abcde@iitm.ac.in
                    title: week-8 discussion
                    status: 1
                    likes: 24
                    is_faq: 0
                    timestamp: '''2023-01-19 03:14:07'
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
        default:
          description: Default error sample response
      tags:
        - Ticket
    put:
      summary: Update Ticket
      description: Update
      operationId: '11'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: Success
          content:
            application/json:
              examples:
                Example 201 Response:
                  value:
                    user_email: abc@iitm.ac.in
                    title: week-9 problem
                    tags: '@arvind'
                    desc: abcd
                    status: 1
                    is_faq: 0
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '403':
          description: Something went wrong
          content:
            application/json:
              examples:
                Example response 403:
                  value: ''
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - Ticket
    delete:
      summary: Delete Ticket
      description: Delete an entry
      operationId: '12'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Content deleted
        '401':
          description: Access Denied
          content:
            application/json:
              examples:
                Example Response 401:
                  value: Access Denied
        '403':
          description: Something went wrong
          content:
            application/json:
              examples:
                Example response 403:
                  value: ''
        '500':
          description: Internal server error
          content:
            application/json:
              examples:
                Example Response 500:
                  value: Internal server error
      tags:
        - Ticket
  /like:
    summary: Returns All Likes
    description: Returns all the Likes done by all the Users on all the Tickets
    get:
      summary: Returns All Likes
      description: Returns all the Likes done by all the Users on all the Tickets
      operationId: ''
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Get All Likes:
                  value:
                    '1':
                      - user1@iitm.ac.in
                      - user2@iitm.ac.in
                    '2':
                      - user1@iitm.ac.in
                      - user3@iitm.ac.in
                      - user4@iitm.ac.in
      tags:
        - Like
  /ticket/{id}/like:
    summary: Returns All Likes, Add Like & Remove Like on Given Ticket
    description: >-
      Returns all the Likes done by all the Users, Add Like & Remove Like by the
      current User on the given Ticket with ticket_id = id
    get:
      summary: Returns All Likes on Given Ticket
      description: >-
        Returns all the Likes done by all the Users on the given Ticket with
        ticket_id = id
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Get All Likes on Given Ticket:
                  value:
                    '1':
                      - user1@iitm.ac.in
                      - user2@iitm.ac.in
      tags:
        - Like
    post:
      summary: Add Like on Given Ticket
      description: Add Like by the current User on the given Ticket with ticket_id = id
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Add Like on Given Ticket:
                  value:
                    ticket_id: 1
                    user_email: user2@iitm.ac.in
      tags:
        - Like
    delete:
      summary: Remove Like on Given Ticket
      description: Remove Like by the current User on the given Ticket with ticket_id = id
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Remove Like on Given Ticket:
                  value:
                    ticket_id: 1
                    user_email: user2@iitm.ac.in
      tags:
        - Like
  /ticket/{id}/content:
    summary: >-
      Returns All Contents of Given Ticket, Returns All Contents by User &
      Create Content for the Given Ticket
    description: >-
      Returns all the Contents of the Given Ticket where ticket_id = id, Returns
      all the Contents by the User where user_email = request.json['email'] &
      Create Ticket for the Given Ticket where ticket_id = id
    get:
      summary: Returns All Contents of Given Ticket
      description: Returns all the Contents of the Given Ticket where ticket_id = id
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Get All Contents of Ticket:
                  value:
                    - id: 1
                      ticket_id: 1
                      user_email: user1@iitm.ac.in
                      text: Example Text
                      image: "\b'Example Image'"
                      timestamp: '2023-03-19 11:59:59'
                    - id: 2
                      ticket_id: 1
                      user_email: user2@iitm.ac.in
                      text: Example Text
                      image: "\b'Example Image'"
                      timestamp: '2023-03-19 11:59:59'
      tags:
        - Content
    post:
      summary: Create Content for the Given Ticket
      description: Create Ticket for the Given Ticket where ticket_id = id
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Create Content:
                  value:
                    id: 4
                    ticket_id: 2
                    user_email: user2@iitm.ac.in
                    text: Example Text
                    image: "\b'Example Image'"
                    timestamp: '2023-03-19 11:59:59'
      tags:
        - Content
  /ticket/{id}/content/{i}:
    summary: Returns Content, Modify Content & Remove Content
    description: >-
      Returns Content of the given content_id = i, Modify Content of the given
      content_id = i & Remove Content of the given content_id = i
    get:
      summary: Returns Content
      description: Returns Content of the given content_id = i
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: i
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Get Content:
                  value:
                    id: 4
                    ticket_id: 2
                    user_email: user2@iitm.ac.in
                    text: Example Text
                    image: "\b'Example Image'"
                    timestamp: '2023-03-19 11:59:59'
      tags:
        - Content
    put:
      summary: Modify Content
      description: Modify Content of the given content_id = i
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: i
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Update Content:
                  value:
                    id: 4
                    ticket_id: 2
                    user_email: user2@iitm.ac.in
                    text: Example Text
                    image: "\b'Example Image'"
                    timestamp: '2023-03-19 11:59:59'
      tags:
        - Content
    delete:
      summary: Remove Content
      description: Remove Content of the given content_id = i
      operationId: ''
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: i
          in: path
          required: true
          schema:
            type: integer
      responses:
        default:
          description: Default error sample response
          content:
            application/json:
              examples:
                Delete Content:
                  value:
                    id: 4
                    ticket_id: 2
                    user_email: user2@iitm.ac.in
                    text: Example Text
                    image: "\b'Example Image'"
                    timestamp: '2023-03-19 11:59:59'
      tags:
        - Content
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          format: max_len = 64
          example: example@iitm.ac.in
        password:
          type: string
          format: max_len = 16
          example: P@ssw0rd
        role:
          type: integer
          format: int
          example: 2
        status:
          type: integer
          format: int
          example: 1
      xml:
        name: user
    Ticket:
      type: object
      properties:
        id:
          type: integer
          format: int
          example: 4
        user_email:
          type: string
          format: max_len = 64
          example: example@iitm.ac.in
        title:
          type: string
          format: max_len = 256
          example: Example Title
        tags:
          type: string
          format: max_len = 64
          example: '#example #tags'
        desc:
          type: string
          format: max_len = 1000
          example: Example Discription
        image:
          type: string
          format: max_len = 1000000
          example: \b'Example Image'
        status:
          type: integer
          format: int
          example: 1
        likes:
          type: integer
          format: int
          example: 4
        is_faq:
          type: boolean
          format: int
          example: 1
        timestamp:
          type: string
          format: timestamp
          example: '2023-03-19 11:59:59'
        contents:
          type: array
          xml:
            name: contents
            wrapped: true
          items:
            $ref: '#/components/schemas/Content'
      xml:
        name: ticket
    Content:
      type: object
      properties:
        id:
          type: integer
          format: int
          example: 4
        user_email:
          type: string
          format: max_len = 64
          example: example@iitm.ac.in
        ticket_id:
          type: integer
          format: int
          example: 4
        text:
          type: string
          format: max_len = 1000
          example: Example Text
        image:
          type: string
          format: max_len = 1000000
          example: \b'Example Image'
        timestamp:
          type: string
          format: timestamp
          example: '2023-03-19 11:59:59'
      xml:
        name: content
    Like:
      type: object
      properties:
        id:
          type: integer
          format: int
          example: 4
        user_email:
          type: string
          format: max_len = 64
          example: example@iitm.ac.in
        ticket_id:
          type: integer
          format: int
          example: 4
      xml:
        name: like